vim.keymap.set('n', '<leader>st', function()
  vim.cmd('vsplit')
  vim.cmd('terminal')
  vim.cmd('startinsert')
end, { noremap = true, silent = true })

vim.keymap.set('n', '<leader>tn', function()
  vim.cmd('vsplit')
  vim.cmd('terminal node')
  vim.cmd('startinsert')
end, { noremap = true, silent = true })
